# Generated by Django 5.2.1 on 2025-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonclone', '0005_order_total_price_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True),
        ),
    ]
