# Generated by Django 5.2.1 on 2025-06-18 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonclone', '0009_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_with_default', to='Amazonclone.address'),
        ),
    ]
