# Generated by Django 5.2.1 on 2025-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonclone', '0011_order_payment_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
