# Generated by Django 5.2.1 on 2025-06-24 05:46

import Amazonclone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonclone', '0015_profile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Amazonclone.models.review_image_upload_path),
        ),
    ]
