# Generated by Django 5.2.1 on 2025-07-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonclone', '0023_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
