# Generated by Django 5.2.1 on 2025-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonclone', '0024_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('appliances', 'Appliances')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
